### PR TITLE
Restructure the git repo and add ability to persist FailedMessages

### PR DESCRIPTION
**Pull request by amcghie**
Restructure the git repo as follows:
- queue-triage-core
  - queue-triage-core-client
  - queue-triage-core-client-test-support
  - queue-triage-core-component-test
  - queue-triage-core-dao
  - queue-triage-core-dao-mongo
  - queue-triage-core-dao-mongo-test-support
  - queue-triage-core-jackson
  - queue-triage-core-server
- queue-triage-web
  - queue-triage-web-server

Added the ability to persist FailedMessages to Mongo.

### CODE REVIEW

**Comment by dwp-enricopelizzon** [comment]
Looks good. The only thing I was thinking is if we should avoid exposing domain objects outside the core layer?

**Comment by amcghie** [comment]
I think that's a really good idea.  Are you thinking something along the lines of changing the `FailedMessageResource` interface to something like:

```java
public interface FailedMessageResource {

    @GET
    @Path("/{failedMessageId}")
    FailedMessageResponse getFailedMessage(@PathParam("failedMessageId") FailedMessageId failedMessgeId);

    @POST
    void create(FailedMessageRequest failedMessageRequest);
}
```

**Comment by dwp-enricopelizzon** [comment]
I was thinking exactly that.

**Comment by amcghie** [comment]
@dwp-enricopelizzon I've pushed my changes to avoid exposing the domain objects.  When you get a moment can you take a look please.

**Pull request merged**
